apiVersion: apps/v1
kind: Deployment
metadata:
  name: zmq-broker
  labels:
    app: zmq-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zmq-broker
  template:
    metadata:
      labels:
        app: zmq-broker
      annotations:
        k8s.v1.cni.cncf.io/networks: '[{ "name": "n3network", "interface": "n3", "ips": [ "{{ .Values.brokerIp }}/24" ] }]'
    spec:
      {{- if .Values.nodeName }}
      nodeName: {{ .Values.nodeName }}
      {{- end }}
      containers:
        - name: broker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: GNB_DL_PORT
              value: "{{ .Values.gnb.dl_port }}"
            - name: GNB_UL_PORT
              value: "{{ .Values.gnb.ul_port }}"
            - name: UES_CONFIG
              value: {{ .Values.ues | toJson | quote }}
      restartPolicy: Always
      dnsPolicy: ClusterFirst

