apiVersion: v1
kind: Service
metadata:
  name: srsran-gnb-ip
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: srsran
    component: gnb
  ports:
    - name: n2
      port: 36412
      targetPort: 36412
      protocol: SCTP
    - name: n3
      port: 2152
      targetPort: 2152
      protocol: UDP
