{{- if .Values.sriov.enabled }}
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: benetel-dpdk-network
  namespace: {{ .Values.sriov.sriovNetworkNamespace }}
spec:
  networkNamespace: {{ .Values.namespace }}
  resourceName: {{ .Values.sriov.sriovResourceName }}
  vlan: {{ .Values.sriov.vlan }}
  spoofChk: "off"
  trust: "on"
  capabilities: '{ "mac": true }'
{{- end }}
