{{- if .Values.sriov.enabled }}
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: benetel-dpdk-policy
  namespace: sriov-network-operator
  labels:
    app: srsran-gnb
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: srsran-gnb
    meta.helm.sh/release-namespace: open5gs
spec:
  deviceType: vfio-pci
  mtu: 9216
  nicSelector:
    rootDevices:
      - "{{ .Values.sriov.rootDevice }}"
  nodeSelector:
    kubernetes.io/hostname: "{{ .Values.nodeName }}"
  numVfs: 4
  priority: 99
  resourceName: {{ .Values.sriov.sriovResourceName }}
{{- end }}
