{{- if .Values.sriov.enabled }}
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: benetel-dpdk-network
  namespace: {{ .Values.sriov.sriovNetworkNamespace }}
spec:
  networkNamespace: {{ .Values.namespace }}
  resourceName: {{ .Values.sriov.sriovResourceName }}
  vlan: {{ .Values.sriov.vlan }}
  spoofChk: "off"
  trust: "on"
  capabilities: '{ "mac": true }'
  pfNames:
    - "{{ .Values.sriov.pfName | default \"ens15f1np1\" }}"
  ipam: |
    {
      "type": "host-local",
      "subnet": "10.56.217.0/24",
      "rangeStart": "10.56.217.171",
      "rangeEnd": "10.56.217.191",
      "routes": [{"dst": "0.0.0.0/0"}],
      "gateway": "10.56.217.1"
    }
{{- end }}

