{{- if .Values.sriov.enabled }}
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: benetel-dpdk-network
  namespace: {{ .Values.sriov.sriovNetworkNamespace }}
  labels:
    app.kubernetes.io/name: srsran-gnb
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  networkNamespace: {{ .Values.namespace }}
  resourceName: {{ .Values.sriov.sriovResourceName }}
  vlan: {{ .Values.sriov.vlan }}
  spoofChk: "off"
  trust: "on"
  deviceType: vfio-pci
  capabilities: '{ "mac": true }'
  ipam: |
    {
      "type": "host-local",
      "subnet": "10.56.217.0/24",
      "rangeStart": "10.56.217.171",
      "rangeEnd": "10.56.217.191",
      "routes": [{"dst": "0.0.0.0/0"}],
      "gateway": "10.56.217.1"
    }
{{- end }}

