# =========================
# srsRAN gNB Dockerfile with ZeroMQ support
# =========================

ARG OS_VERSION=24.04

# =========================
# Stage 1: Build Stage
# =========================
FROM ubuntu:$OS_VERSION AS builder

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    cmake \
    make \
    gcc \
    g++ \
    pkg-config \
    libfftw3-dev \
    libmbedtls-dev \
    libsctp-dev \
    libyaml-cpp-dev \
    libgtest-dev \
    libzmq3-dev \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN git clone --depth 1 --branch csi https://github.com/turletti/srsRAN_Project.git /src

# Build srsRAN with ZeroMQ enabled
WORKDIR /src

RUN mkdir build && cd build && \
    cmake ../ -DENABLE_EXPORT=ON -DENABLE_ZEROMQ=ON -DCMAKE_INSTALL_PREFIX=/opt/srs && \
    make -j$(nproc)

RUN cp /src/build/apps/cu/srscu             /tmp/srscu                     && \
    cp /src/build/apps/du/srsdu             /tmp/srsdu                     && \
    cp /src/build/apps/gnb/gnb              /tmp/gnb                       && \
    cd /src/build                                                          && \
    make install                                                           && \
    mv /tmp/srscu                           /opt/srs/bin/srscu             && \
    mv /tmp/srsdu                           /opt/srs/bin/srsdu             && \
    mv /tmp/gnb                             /opt/srs/bin/gnb

# =========================
# Stage 2: Runtime Stage
# =========================
FROM ubuntu:$OS_VERSION

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    libfftw3-dev \
    libmbedtls-dev \
    libsctp-dev \
    libyaml-cpp-dev \
    libgtest-dev \
    libzmq3-dev \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /opt/srs /usr/local
