# =========================
# Work in progress, still UNTESTED
# values from https://github.com/srsran/srsRAN_Project/blob/main/configs/gnb_ru_ran550_tdd_n78_100mhz_4x2.yml
# gNB values file for DPDK setup with Benetel.
# =========================

image:
  repository: r2labuser/srsran-gnb-dpdk # including iproute2/ping/tcpdump
  tag: v1.0
  pullPolicy: IfNotPresent

start:
  gnb: true          # If false, the gNB container will just sleep and not start srsRAN gNB
  logs: true         # If false, the gnb-log container will not be deployed

gnbIp: 10.10.3.231

gnbConfig:
  hal:
    eal_args: "--lcores (0-1)@(0-23)"
  cu_cp:
    inactivity_timer: 7200
    request_pdu_session_timeout: 30
    amf:
      sctp_rto_initial: 200
      sctp_rto_min: 200
      sctp_rto_max: 2000
      sctp_init_max_attempts: 5
      sctp_hb_interval: 1000
      sctp_assoc_max_retx: 5
      sctp_nodelay: true
      addr: 10.10.3.200
      port: 38412
      bind_addr: 10.10.3.231
      supported_tracking_areas:
        - tac: 1
          plmn_list:
            - plmn: "00101"
              tai_slice_support_list:
                - sst: 1
                - sst: 1
                  sd: "000002"
  ru_ofh:
    t1a_max_cp_dl: 535
    t1a_min_cp_dl: 286
    t1a_max_cp_ul: 535
    t1a_min_cp_ul: 286
    t1a_max_up: 390
    t1a_min_up: 80
    ta4_max: 500
    ta4_min: 25
    is_prach_cp_enabled: true
    compr_method_ul: bfp
    compr_bitwidth_ul: 9
    compr_method_dl: bfp
    compr_bitwidth_dl: 9
    compr_method_prach: bfp
    compr_bitwidth_prach: 9
    enable_ul_static_compr_hdr: false
    enable_dl_static_compr_hdr: false
    iq_scaling: 5.5
    cells:
      - network_interface: ru
        ru_mac_addr: 8c:1f:64:d1:12:8c # specific to benetel1
        du_mac_addr: 00:11:22:33:44:66 # 80:61:5f:0d:df:aa
        vlan_tag_cp: 801 # specific to benetel1
        vlan_tag_up: 801 # specific to benetel1
        prach_port_id: [4, 5]
        dl_port_id: [0, 1, 2, 3]
        ul_port_id: [0, 1]
  cell_cfg:
    dl_arfcn: 637212
    band: 78
    channel_bandwidth_MHz: 100
    common_scs: 30
    plmn: "00101"
    tac: 1
    pci: 1
    nof_antennas_dl: 4
    nof_antennas_ul: 2
    prach:
      prach_config_index: 159
      prach_root_sequence_index: 1
      zero_correlation_zone: 0
    ssb:
      ssb_block_power_dbm: -4
    tdd_ul_dl_cfg:
      dl_ul_tx_period: 10
      nof_dl_slots: 7
      nof_dl_symbols: 6
      nof_ul_slots: 2
      nof_ul_symbols: 4
    slicing:
      - sst: 1
      - sst: 1
        sd: "000002"
  log:
    filename: /tmp/gnb.log
    all_level: warning
    config_level: debug
  metrics:
    enable_log: false
    autostart_stdout_metrics: true
    enable_json: true
    layers:
      enable_app_usage: true
      enable_e1ap: true
      enable_pdcp: true
      enable_sched: true
      enable_rlc: true
      enable_mac: true
      enable_executor: true
      enable_du_low: true
      enable_ru: true
  pcap:
    mac_enable: false
    mac_filename: /tmp/gnb_mac.pcap
    ngap_enable: false
    ngap_filename: /tmp/gnb_ngap.pcap
  remote_control:
    bind_addr: 0.0.0.0
    enabled: true
    port: 8001
sriov:
  name: "ru"
  type: sriov
  mac: "00:11:22:33:44:66"
  pciAddress: "0000:3a:09.3"
  sriovNetworkNamespace: "sriov-network-operator"
  sriovResourceName: "ruvfiou"
  vlan: 801
 