# =========================
# srsUE values file for basic ZMQ setup.
# =========================

image:
  repository: docker.io/r2labuser/srsue
  #repository: ghcr.io/ziyad-mabrouk/srsue
  #tag: v1.0
  tag: latest
  pullPolicy: IfNotPresent

# injected by ansible
gnbIp: ""
ueIp: ""

